runs:
  using: 'composite'
  steps:
    - name: Add Project Key to Dependabot Configuration File
      run: |
        projectKey=$(cat .github/workflows/master_pull_request.yaml|grep 'projectKey:'|awk -F ':' '{print $2}'|xargs echo)
        sed -i "s/prefix:.*/prefix: ${projectKey}-0/g" .github/dependabot.yml
      shell: bash
    - name: Commit and push changes
      run: | 
        git add . |
        git commit -m "Updating dependabot.yml"
        git fetch origin
        git push origin HEAD:main
      shell: bash
      