name: Add Project Key to Dependabot

on:
  push:
    branches-ignore:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Validate-PR-Prefix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add Project Key to Dependabot
        uses: ./.github/actions/patch-project-key

      - name: Update files on GitHub
        uses: test-room-7/action-update-file@v1.6.0
        with:
          file-path: .github/dependabot.yml
          commit-msg: Add Dependabot Project Key
          github-token: ${{ secrets.GITHUB_TOKEN }}
