name: Verify Dependabot Project Key 

on:
  pull_request:
    branches:
      - 'main'
      - 'master'
    paths:
      - '.github/dependabot.yml'
      - '.github/workflows/master_pull_request.yaml'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Verify-Dependabot-Project-Key:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v2

      # - name: Add Project Key to Dependabot
      # uses: ./.github/actions/add-project-key

      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Add Project Key to Dependabot Configuration File
        run: |
          projectKey=$(cat .github/workflows/master_pull_request.yaml|grep 'projectKey:'|awk -F ':' '{print $2}'|xargs echo)
          sed -i "s/prefix:.*/prefix: ${projectKey}-0/g" .github/dependabot.yml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Add Project Key"
        shell: bash

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
