name: Verify Dependabot Project Key 

on:
  pull_request:
    branches:
      - 'main'
      - 'master'
    paths:
      - '.github/dependabot.yml'
      - '.github/workflows/master_pull_request.yaml'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Verify-Dependabot-Project-Key:
    runs-on: ubuntu-latest

    steps:
      - name: Add Project Key to Dependabot
        uses: ./.github/actions/add-project-key
