name: Validate Source Code

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Validate-Source-Code:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce Jira Issue Key in Pull Request Title
        uses: ryanvade/enforce-pr-title-style-action@v1
        if: ${{ github.actor != 'dependabot[bot]'}}
        with:
          projectKey: RICKY

      - uses: actions/checkout@v2