name: Validate Source Code

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Validate-Source-Code:
    runs-on: ubuntu-latest
    steps:
      - name: View PR author
        run: echo "This PR is opened by ${{ github.event.pull_request.user.login }} ."
      - name: View Expected
        run: |
          echo dependabot[bot]
          echo ${{ github.event.pull_request.user.login }} != 'dependabot[bot]'}}
      - name: Enforce Jira Issue Key in Pull Request Title
        uses: ryanvade/enforce-pr-title-style-action@v1
        if: ${{ github.event.pull_request.user.login }} != 'dependabot[bot]'}}
        with:
          projectKey: RICKY

      - uses: actions/checkout@v2